import { describe, expect, it } from 'vitest';
import { alertKind, effectivePrice, priceCopy, priceStats, suggestTarget, validTarget, type PricePoint } from '../src/price';
const DAY = 86400000;
const now = 200 * DAY;
const p = (price: number, age = 0, shipping_fee = 0): PricePoint => ({ price, shipping_fee, observed_at: now - age * DAY });
describe('price calculations', () => {
  it('includes shipping', () => expect(effectivePrice(100, 60)).toBe(160));
  it('defaults missing shipping to zero', () => expect(effectivePrice(100)).toBe(100));
  it.each([-1, 1.1, NaN, Infinity])('rejects invalid amount %s', value => expect(() => effectivePrice(value)).toThrow());
  it('rejects negative shipping', () => expect(() => effectivePrice(100, -10)).toThrow());
  it('empty stats are entirely null', () => expect(Object.values(priceStats([], now)).every(v => v === null)).toBe(true));
  it('uses chronological current', () => expect(priceStats([p(100), p(200, 1)], now).current).toBe(100));
  it('adds shipping to stats', () => expect(priceStats([p(90, 0, 60), p(120, 1)], now).low).toBe(120));
  it('tracks low timestamp', () => expect(priceStats([p(120), p(90, 2)], now).lowAt).toBe(now - 2 * DAY));
  it('tracks high', () => expect(priceStats([p(120), p(90, 2)], now).high).toBe(120));
  it('filters old observations', () => expect(priceStats([p(1, 181), p(100)], now).low).toBe(100));
  it('includes boundary', () => expect(priceStats([p(1, 180)], now).sampleCount).toBe(1));
  it('filters future observations', () => expect(priceStats([p(1, -1)], now).current).toBeNull());
  it('supports custom window', () => expect(priceStats([p(1, 31)], now, 30).current).toBeNull());
  it('does not mutate the input', () => { const points = [p(100), p(80, 1)]; priceStats(points, now); expect(points[0]?.price).toBe(100); });
  it('tracks coverage', () => expect(priceStats([p(120), p(90, 3)], now).coverageDays).toBe(3));
  it('retains flat samples', () => expect(priceStats([p(100), p(100, 1)], now).sampleCount).toBe(2));
  it('avoids a lowest claim on first observation', () => expect(priceCopy(priceStats([p(122)], now))).toBe('現在 NT$122（第一次觀測，還沒有比較基準）'));
  it('uses actual coverage in copy', () => expect(priceCopy(priceStats([p(122), p(123, 3)], now))).toContain('3 天'));
  it('suggests 2% above low', () => expect(suggestTarget(priceStats([p(120), p(100, 1)], now))).toBe(102));
  it('suggests 5% below current low', () => expect(suggestTarget(priceStats([p(100), p(120, 1)], now))).toBe(95));
  it('keeps suggestion below current', () => expect(suggestTarget(priceStats([p(101), p(100, 1)], now))).toBe(100));
  it('does not invent a target with no data', () => expect(suggestTarget(priceStats([], now))).toBeNull());
  it('handles minimum whole-dollar price', () => expect(suggestTarget(priceStats([p(1)], now))).toBeNull());
  it.each([0, -1, 1.2, 100, 101, '90', null, NaN])('rejects invalid target %s', value => expect(validTarget(value, 100)).toBe(false));
  it('accepts positive integer below current', () => expect(validTarget(90, 100)).toBe(true));
  it('target wins over new low', () => expect(alertKind(90, 90, 100, null, now)).toBe('target_hit'));
  it('detects new low', () => expect(alertKind(95, 90, 100, null, now)).toBe('new_low'));
  it('does not label first sample a new low', () => expect(alertKind(95, 90, null, null, now)).toBeNull());
  it('equal low is not new low', () => expect(alertKind(100, 90, 100, null, now)).toBeNull());
  it('respects cooldown', () => expect(alertKind(80, 90, 100, now - 19 * 3600000, now)).toBeNull());
  it('allows alert at 20 hours', () => expect(alertKind(80, 90, 100, now - 20 * 3600000, now)).toBe('target_hit'));
});
